'use strict';
const el=id=>document.getElementById(id);
let records=[],groups=[],selected=null,approved=null,published=null;
const message=text=>{el('status').textContent=text;};
async function api(path,body){const r=await fetch('/api/localization-review/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw new Error(d.detail||'保存失败');return d;}
function selectCandidate(record,node){el('machine-review').hidden=true;approved=null;published=null;el('publication').hidden=true;el('engagement').hidden=true;selected=record;el('edited').value=record.text;el('reason').value='';el('categories').value='';el('editor').hidden=false;document.querySelectorAll('.candidate').forEach(n=>n.classList.remove('selected'));node.classList.add('selected');}
function showGroup(){el('machine-review').hidden=true;selected=null;approved=null;published=null;el('editor').hidden=true;el('publication').hidden=true;el('engagement').hidden=true;const group=groups[Number(el('sources').value)];if(!group)return;const source=group[0].source;el('original').textContent=source.original_text;el('provenance').textContent=[source.author_name,source.published_at,source.url].filter(Boolean).join(' · ');el('candidates').replaceChildren();group.forEach((record,i)=>{const card=document.createElement('article');card.className='candidate';const title=document.createElement('h2');title.textContent='候选 '+String.fromCharCode(65+i)+' · '+record.account_id;const copy=document.createElement('div');copy.className='copy';copy.textContent=record.text;const button=document.createElement('button');button.textContent='选择这份稿件进行审核';button.onclick=()=>selectCandidate(record,card);card.append(title,copy,button);el('candidates').append(card);});}
el('sources').onchange=showGroup;
el('review-form').onsubmit=async event=>{event.preventDefault();if(!selected)return;try{const review=await api('reviews',{candidate_id:selected.id,expected_version:selected.draft_version,edited_text:el('edited').value,decision:event.submitter.value,reviewer:el('reviewer').value,reason:el('reason').value,categories:el('categories').value.split(/[,，]/).map(s=>s.trim()).filter(Boolean)});message('已保存审核与修改记录；未执行发布。');el('machine-review').hidden=false;el('machine-detail').textContent=JSON.stringify(review.machine_review_after_submission,null,2);approved=review.decision==='approve'?review:null;published=null;el('engagement').hidden=true;el('publication').hidden=!approved;}catch(e){message(e.message);}};
el('publication-form').onsubmit=async event=>{event.preventDefault();if(!approved)return;try{published=await api('publications',{review_id:approved.id,platform:el('platform').value,published_post_id:el('post-id').value,published_at:el('published-at').value,published_text_hash:approved.human_draft_version,url:el('post-url').value||null});el('engagement').hidden=false;el('observed-at').value=new Date().toISOString();message('已保存发布关联。');}catch(e){message(e.message);}};
el('engagement-form').onsubmit=async event=>{event.preventDefault();if(!published)return;try{await api('engagement',{publication_id:published.id,observed_at:el('observed-at').value,metrics:{views:Number(el('views').value),likes:Number(el('likes').value)},provenance:el('metric-source').value});message('已保存表现快照。');}catch(e){message(e.message);}};
api('candidates').then(data=>{records=data;const index=new Map();for(const r of records){const k=r.source.source_hash+'|'+r.account_id;if(!index.has(k))index.set(k,[]);index.get(k).push(r);}groups=[...index.values()];groups.forEach((g,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(g[0].source.author_name||'来源')+' · '+g[0].account_id+' · '+g.length+' 份候选';el('sources').append(o);});if(!groups.length)message('尚无已登记的候选稿。');showGroup();}).catch(e=>message(e.message));
