"""Summarize actual artifacts and runs; missing gates stay explicitly incomplete."""
from pathlib import Path
import json,csv,sqlite3,collections,datetime,hashlib
ROOT=Path(__file__).resolve().parents[1]
def read(p,default=None):
 q=ROOT/p
 return json.loads(q.read_text()) if q.exists() else default
def write(p,v):
 (ROOT/p).write_text(json.dumps(v,ensure_ascii=False,indent=2))
def main():
 now=datetime.datetime.now(datetime.timezone.utc).isoformat();m=read('data/corpus_manifest.json');ml=read('ml_experiments/run_summary.json');cleanup=read('runs/promotion-cleanup.json');language=read('runs/language-coverage.json');d=read('ml_experiments/D_guarded_generation_ablation.json',{});v=read('runs/validation.json',{})
 with sqlite3.connect(ROOT/'data/lab.sqlite') as c:counts=dict(c.execute('SELECT kind,count(*) FROM records GROUP BY kind'))
 calls=[json.loads(p.read_text()) for p in (ROOT/'runs/model_calls').glob('*.json')];completed=[r for r in calls if r.get('status')=='completed'];no_completion=[r['run_id'] for r in calls if r.get('status')=='started'];purpose=collections.Counter(r.get('task','unknown') for r in completed)
 tokens={k:sum(r.get('usage',{}).get(k,0) for r in completed) for k in ['prompt_tokens','completion_tokens','total_tokens']}
 frameworks=sum(len(read(str(p.relative_to(ROOT)),{}).get('model_enrichment',{}).get('frameworks',[])) for p in (ROOT/'knowledge_profiles').glob('*.json'))
 blockers=[{'gate':'donor_language_coverage','status':'incomplete','actual':language,'required':'>=6 authors with >=150 Chinese original finance posts each and >=6 authors with >=150 English posts each; complete 180-day windows or documented capped 500 samples'},
 {'gate':'new_x_collection','status':'awaiting_account_and_cost_preflight','required':'XQUIK_API_KEY and approved extraction cost ceiling; selected collector only','new_requests':0},
 {'gate':'human_blind_review_and_edit','status':'complete' if counts.get('human-review',0) else 'awaiting_real_human','actual_submissions':counts.get('human-review',0)},
 {'gate':'generation_quality','status':'not_validated','reason':'Concrete unsupported inferences survive same-model diagnostics. Five-mode results contain schema, citation and factual failures. No persona quality improvement established.'},
 {'gate':'knowledge_frameworks','status':'partial','accepted_same_model_proxy_frameworks':frameworks,'reason':'Sparse same-donor multi-post support; accepted candidates still lack independent semantic review.'},
 {'gate':'sec_mcp','status':'disabled','required':'Real SEC_EDGAR_USER_AGENT contact identity. Issuer-hosted 10-Q available; independent SEC retrieval not executed.'},
 {'gate':'browser_replay','status':'partial','reason':'Existing Chrome window corpus checks only; user later navigated away. No new browser or restart. Four-page API verification does not equal complete browser E2E.'},
 {'gate':'continuous_current_events','status':'not_implemented','reason':'Actual captured primary releases replay through versioned ingestion; no continuous live event collection or alert scheduler.'}]
 runstats={'as_of':now,'model_call_files':len(calls),'completed_calls':len(completed),'calls_by_purpose':dict(purpose),'status_counts':dict(collections.Counter(r.get('status','legacy_unlabeled') for r in calls)),'no_completion_record_ids':no_completion,'tokens_in_completed_records':tokens,'paid_model_api_cost':0,'cost_scope':'Local inference: excludes hardware, electricity, internet and prior source-provider charges. Public model downloads incur no model API charge. SDK operation counts are not wire-level HTTP counts.','old_interruption_record':'runs/knowledge-interruption.json','live_x_calls':0,'live_sec_calls':0}
 write('runs/run-ledger-summary.json',runstats);write('blockers.json',{'as_of':now,'acceptance':'incomplete','gates':blockers})
 matrix=[]
 def item(skill,state,artifacts,runs,data,metrics,frontend):matrix.append({'skill':skill,'status':state,'artifacts':artifacts,'run_records':runs,'actual_data':data,'metrics':metrics,'frontend_replay':frontend})
 item('jupyter-notebook','installed and executed',['ml_experiments/corpus_baselines.ipynb'],['runs/notebook-execution.json'],{'raw':m['raw_posts'],'review_scored':300},read('ml_experiments/notebook_metrics.json'),'Persona Lab comparison; notebook has executed outputs, not embedded interactive notebook')
 item('playwright','installed; existing browser attach unavailable',[],['runs/playwright-attach-preflight.json','runs/browser-verification.json'],{'sessions':0,'automated_e2e_runs':0},None,'Partial authorized native Chrome inspection; full Playwright replay pending')
 item('screenshot','installed; system permission preflight rejected',['data/evidence/nvidia-q2-fy2027-income-statement.png'],['runs/official-pdf-capture.json','runs/browser-verification.json'],{'os_screenshot_runs':0,'source_pdf_pages_rendered':1},None,'Persona Lab issuer page image; PDF rendering is a distinct fallback, not execution of screenshot skill')
 item('x-twitter-scraper / Xquik','selected, installed, disabled',['data/raw_posts.jsonl','data/clean_posts.jsonl','skill-audit/credential-scope-test.json'],['skill-audit/skills.lock.json'],{'new_x_requests':0,'existing_import_raw':m['raw_posts'],'existing_import_clean':m['clean_posts']},None,'Corpus Explorer shows imported source files; no claim that Xquik produced them')
 item('huggingface-trackio','installed and executed locally',['ml_experiments/trackio'],['ml_experiments/run_summary.json'],{'A':300,'B':360},ml['authorship'],'Persona Lab actual metric tables; Trackio records local only')
 item('train-sentence-transformers','evaluated, deferred',['ml_experiments/embedding_manifest.json'],['ml_experiments/run_summary.json'],{'frozen_embedding_posts':m['raw_posts'],'finetuning_runs':0},ml['classification']['pretrained_embedding_logistic'],'Frozen-model results only; no training claim')
 item('huggingface-community-evals','evaluated, deferred',['ml_experiments/A_finance_classification.json','ml_experiments/B_authorship.json'],['ml_experiments/run_summary.json'],{'community_eval_runs':0},None,'Project-specific local tests are separately reported, not community benchmark results')
 for skill in ['yfinance-data','earnings-recap','estimate-analysis']:
  item(skill,'installed and used; financial comparison qualified',['data/finance_supplement/nvda.json','data/finance_supplement/earnings-recap-and-estimate-analysis.json'],['runs/api_run_ledger.jsonl','runs/official-pdf-capture.json'],{'tickers':1,'earnings_history_rows':4,'earnings_estimate_rows':4,'revenue_estimate_rows':4,'sdk_operations':3}, {'GAAP_EPS':2.46,'nonGAAP_EPS':2.22,'consensus_basis_independently_verified':False},'Persona Lab, issuer 10-Q image and basis comparison')
 item('SEC EDGAR MCP','audited and installed; identity preflight blocks execution',['scripts/sec_mcp_entry.py','skill-audit/sec-edgar-mcp.disabled.json'],['runs/sec-mcp-preflight.json'],{'SEC_network_requests':0},None,'No SEC live replay; issuer-hosted source is separately identified')
 item('financial-persona-distillation','created, validated and used; quality gate incomplete',['knowledge_profiles','style_profiles','content_habit_profiles','personas','generated_samples','cross_language_tests'],['ml_experiments/run_summary.json','ml_experiments/D_guarded_generation_ablation.json','runs/automated-editorial-reviews.json'],{'profiles_per_type':12,'personas':3,'human_reviews':counts.get('human-review',0),'guarded_passed':len(d.get('rows',[])),'guarded_failed':len(d.get('failures',[]))},ml['authorship'],'Corpus Explorer / Persona Lab / Live Studio / Update & Handoff')
 write('skill-audit/skill-product-run-matrix.json',{'as_of':now,'installation_is_progress':False,'rows':matrix})
 with (ROOT/'skill-audit/skill-product-run-matrix.csv').open('w',encoding='utf-8-sig',newline='') as f:
  w=csv.DictWriter(f,fieldnames=matrix[0].keys());w.writeheader();w.writerows({k:json.dumps(val,ensure_ascii=False) if isinstance(val,(dict,list)) else val for k,val in r.items()} for r in matrix)
 report={'as_of':now,'acceptance':'incomplete executable research slice; not accepted MVP','corpus':{'raw':m['raw_posts'],'clean':m['clean_posts'],'language':language,'promotion_cleanup':cleanup},'ml':ml,'D':d,'model_runs':runstats,'records':counts,'validation':v,'blockers':blockers,'human_scores':None,'validator_calibration':read('runs/validator-calibration.json',{}),'operational_repair':read('runs/generation-repair-v4.json',{}),'cross_language_review':read('cross_language_tests/automated-review.json',{})}
 write('evaluation_report.json',report)
 lines=['# 实施与评估结果',f'截至 {now}。这是有真实数据和运行记录的研究实现，**尚未达到任务书验收标准**。','','| 实际产物 | 结果 |','|---|---|',f'| 原始 / 清洗帖子 | {m["raw_posts"]} / {m["clean_posts"]}；原始输入哈希未变 |',f'| 推广处理 | 384 个固定尾注、3 段商业尾文、1 段内嵌导流；另排除 13 条整帖商业内容。保留语料显式推广规则命中为 0 |','| 复核表 | 517 条严格规则复核；300 条明确参考标签，217 条拒判；真人标签为 0 |',f'| 作者配额 | 只有 {language["donors_reaching_150_zh"]} 位中文和 {language["donors_reaching_150_en"]} 位英文作者达到各自 150 条；名单语言不能替代帖子语言 |',f'| 五条件生成 | 最新完整设计 30 格；目前通过结构 / 数字门槛 {len(d.get("rows",[]))}，失败 {len(d.get("failures",[]))}；通过不等于内容合格 |',f'| 人设 / 三类画像 | 3 个原创组合、每类 12 份画像；仅 {frameworks} 个知识框架通过多帖支持的同模型诊断 |',f'| 真人盲评 | {counts.get("human-review",0)} 条真实提交 |',f'| 数据与 API 校验 | {v.get("passed",0)} 通过，{v.get("failed",0)} 失败；完整浏览器 E2E 尚未完成 |','','金融分类 A 在同一批 300 条严格规则参考上比较；规则 F1=1 是规则同源性，不能当作人工准确率。','', '| 方法 | 宏 F1 | 评估数 |','|---|---:|---:|']
 for name,x in ml['classification'].items():lines.append(f'| {name} | {x["macro_f1"]:.4f} | {x["n"]} |')
 lines+=['','7B LLM 请求 300 条，298 条返回有效类别；拒判 2 条。217 条缓存是同提示、同系统指令、同模型提交和参数的既有真实请求，83 条新推理。','', '作者识别 B：按时间留出，排除交叉线程及完全重复内容；6 位训练/测试量足够的作者、360 条测试。这里的资格门槛不是每位 150 条的语料验收门槛。','', '| 特征 | 宏 F1 |','|---|---:|']
 for name,x in ml['authorship'].items():lines.append(f'| {name} | {x["macro_f1"]:.4f} |')
 lines+=['','C 为全语料的 8 个探索性主题聚类、12 位作者分布与 66 对兼容性；240 对同题、跨时间文本做 self-similarity。它不是预测回测收益，也不构成纯风格相似度的理论上限。', '', 'D 每格只有一次样本，不能据此证明人设组合优于基线。早期受推广污染的版本及失败模型输出单独保留；不同模型与生成约束同时变化，因此不能把差异全归因于模型大小。真实复核已经发现“上修即延迟招聘”“失业率不变即参与率未提升”等错误；同模型检查未拦住它们。详见 `runs/automated-editorial-reviews.json`，原始稿和调用没有覆盖。', '', 'Notebook 使用另一组 TF-IDF 特征上限，宏 F1 0.8252；配置不同，不应与主实验 0.8962 当成同一结果。全部模型为固定公开权重本地运行；未启动 LoRA/SFT、未上传语料。', '', '三类视觉分别是：随稿件证据版本重算的数据图、公司原始 10-Q 页面图、由实际事实引用和未来日历节点生成的可编辑结构图。源图不替代正文事实核验。', '', '跨语言转换已实际运行两个方向，但不能判合格：中文转英文把“不能据此认定政策预期过度乐观”译成了政策预期确实过度乐观。逐字检查见 `cross_language_tests/automated-review.json`；这条是 AI 检查，不是真人盲评。', '', '独立的 v4 接口修复测了 3 人设 × 2 语言的 multi 模式，3 格通过、3 格被校验拒绝；不改写前面的 30 格消融结果。v4.1 另修复了英文 lacks 与 negative 数字表述造成的误报，重放原始模型响应并单独记录，未将其计作新生成成功。见 `runs/generation-repair-v4.json`、`runs/validator-calibration.json`。拒绝数不是内容错误率，自动校验存在误报与漏报。', '', '真实调用与成本：', '', f'- 已保存 {len(calls)} 个模型调用文件，其中 {len(completed)} 个有完成记录；状态和 token 明细见 `runs/run-ledger-summary.json`。', '- 本地模型付费 API 成本为 0；没有计入硬件、电力、网络和既有数据供应商历史费用。Yahoo 的 3 次 SDK 操作不能声称只有 3 个底层 HTTP 请求。', '- 新 X 请求 0；SEC 网络请求 0。缺少各自所需的凭证/身份，不能伪造已运行状态。', '', '待完成门槛：', '']
 lines.extend('- '+x['gate']+'：'+x['status']+'。'+x.get('reason',x.get('required','')) for x in blockers)
 lines+=['','从 `启动.md` 打开实际页面；技能决策见 `skill-audit/audit.md`，每个 skill 的产物、数据量、指标与前端入口见 `skill-audit/skill-product-run-matrix.json`。']
 (ROOT/'evaluation_report.md').write_text('\n'.join(lines)+'\n')
 print(json.dumps({'report_written':True,'completed_calls':len(completed),'guarded_cells':len(d.get('rows',[]))+len(d.get('failures',[])),'human_reviews':counts.get('human-review',0)}))
if __name__=='__main__':main()
